### ISSUE TITLE
Old URLs in RAW Data section 

### ISSUE THREAD

**Issue by unclenate** [cogsec-collaborative/AMITT#2]
https://github.com/cogsec-collaborative/AMITT/blob/main/AMITT_MASTER_DATA/amitt_metadata_v3.xlsx

"/blob" should be changed to "/tree" to reflect the correct location and not produce a "404" in documentation. At least one .XLS reference is broken.

**Comment by bodacea** [comment]
Have fixed this now, using a relative link.  Thank you for reporting!
